<?php
/**
 * Created by PhpStorm.
 * User: letuananh
 * Date: 2/13/17
 * Time: 14:41:09
 */

namespace App\Libraries\DynamicFormManager\Widgets;


class Select extends ChoiceWidget
{
    protected $inputType = 'select';
    protected $templateName = 'DynamicForm::select';
    protected $optionTemplateName = 'DynamicForm::select_option';

    protected $addIdIndex = false;
    protected $checkedAttribute = ['selected' => true];

    public function getContext($name, $value, $attrs = ['class' => 'form-control form-medium'])
    {
        $context = parent::getContext($name, $value, $attrs); // TODO: Change the autogenerated stub
        if ($this->allowMultipleSelected) {
            $context['widget']['attrs']['multiple'] = 'multiple';
        }
        return $context;
    }

    public function displayData($data, $name)
    {
        if (isset($this->choices[$this->dataFromArray($data, $name)])) {
            return $this->choices[$this->dataFromArray($data, $name)];
        }else {
            return parent::displayData($data, $name);
        }

    }
}